# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Manasvini Sethuraman
description:          'Ph.D. Student @ GaTech'
#description:      'I am a 4th year Ph.D. student in the Embedded Pervasive Lab led by Dr. Kishore Ramachandran at Georgia Tech. My interests lie in distributed systems, internet measurement, and edge computing.'
url:              https://manasvini.github.io
baseurl:          /
# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Manasvini/Manasvini.github.io
