# Dependencies
markdown:         kramdown
highlighter:      pygments
theme:            null
# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Manasvini Sethuraman
description:          'Curious about  human languages, software and history, in no specific order.'
url:              https://manasvini.github.io
baseurl:          https://manasvini.github.io/about

paginate:         5
# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Manasvini/Manasvini.github.io
